project:
  type: website
  output-dir: docs

render:
  ignore:

website:
  title: "BU METER"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: METER_Sample_Size-SHORT_Quarto.html
        text: Sample Size

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



