project:
  type: website
  output-dir: docs

render:
  ignore:

website:
  title: "BU METER"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: METER_Sample_Size-SHORT-Quarto.html
        text: Sample Size
      - href: METER_Inference-SHORT-Quarto.html
        text: Inference
      - href: METER_P_Values-Quarto.html
        text: P-values

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



